---

- name: "Install Nginx"
  hosts: all
  gather_facts: yes
  vars:
    nginx_packages: nginx

  tasks:
    - name: Install Nginx packages
      package: 
        name: "{{ nginx_packages }}"
        state: latest
      become: yes

    - name: Start service
      service:
        name: nginx
        state: started
        enabled: yes
      become: yes
