---
# tasks file for roles/nginx_webserver
- name: Install packages
  package:
    name: "{{ webserver_packages }}"
    state: latest

- name: Enable service
  service:
    name: nginx
    enabled: yes
    state: started

- name: Add base NGINX configuration file
  copy:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload NGINX

- name: Add static site config files
  template:
    src: site.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ webserver_static_sites }}"
  notify: Reload NGINX